# Generated by Django 5.0.1 on 2024-01-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipenext', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='Recipenext.recipe'),
        ),
    ]
